#!/usr/bin/env node
/**
 * MedTrack Setup Script
 * Generates .env.local with auto-created secrets.
 * You only need to paste 3 values from Supabase (takes ~2 minutes).
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const ENV_PATH = path.join(ROOT, '.env.local');

function generateVapidKeys() {
  try {
    const out = execSync('npx web-push generate-vapid-keys', { encoding: 'utf8', cwd: ROOT });
    const pub = out.match(/Public Key:\s*\n(\S+)/)?.[1];
    const priv = out.match(/Private Key:\s*\n(\S+)/)?.[1];
    if (pub && priv) return { publicKey: pub, privateKey: priv };
  } catch {
    // fallback
  }
  return {
    publicKey: 'BI41fdWpsgjHupGktIPZAwK8LlbYZcVXteso5gG4iHIPzWW8Lx46b0yIxaCLgaqwawjjALEBLGabYnAPuog0bcY',
    privateKey: 'vuMox7qbW_OQ7ZEtKWv58KRRLHgFiuOfvmFidNK4SFU',
  };
}

const vapid = generateVapidKeys();
const cronSecret = crypto.randomBytes(32).toString('hex');

const envContent = `# ============================================================
# MedTrack — Auto-generated by: npm run setup
# ============================================================

# --- STEP 1: Paste these 3 values from Supabase Dashboard ---
# Go to: https://supabase.com/dashboard → Your Project → Settings → API
NEXT_PUBLIC_SUPABASE_URL=PASTE_YOUR_SUPABASE_URL_HERE
NEXT_PUBLIC_SUPABASE_ANON_KEY=PASTE_YOUR_ANON_KEY_HERE
SUPABASE_SERVICE_ROLE_KEY=PASTE_YOUR_SERVICE_ROLE_KEY_HERE

# --- Auto-configured (do not change) ---
NEXT_PUBLIC_SITE_URL=https://medtrack-flame.vercel.app
KIOSK_PIN=1234
CRON_SECRET=${cronSecret}
NEXT_PUBLIC_VAPID_PUBLIC_KEY=${vapid.publicKey}
VAPID_PRIVATE_KEY=${vapid.privateKey}
VAPID_SUBJECT=mailto:caregiver@medtrack.app

# --- Optional: Google Tasks (skip for now, add later) ---
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
`;

if (fs.existsSync(ENV_PATH)) {
  console.log('⚠️  .env.local already exists — writing .env.local.new instead');
  fs.writeFileSync(path.join(ROOT, '.env.local.new'), envContent);
} else {
  fs.writeFileSync(ENV_PATH, envContent);
  console.log('✅ Created .env.local');
}

console.log(`
╔══════════════════════════════════════════════════════════════╗
║           MedTrack Setup — 3 steps (~5 minutes)              ║
╚══════════════════════════════════════════════════════════════╝

STEP 1 — Create Supabase project (free)
  → Open: https://supabase.com/dashboard/new/new-project
  → Name: medtrack  |  Password: (save it)  |  Region: closest to you
  → Wait ~2 min for project to finish creating

STEP 2 — Run database setup
  → Open: Supabase Dashboard → SQL Editor → New query
  → Copy ALL of: supabase/SETUP-ALL-IN-ONE.sql
  → Paste → Click "Run"
  → Then: Authentication → Providers → Email → Enable "Email" provider

STEP 3 — Paste API keys into .env.local
  → Supabase Dashboard → Settings → API
  → Copy "Project URL"        → NEXT_PUBLIC_SUPABASE_URL
  → Copy "anon public" key    → NEXT_PUBLIC_SUPABASE_ANON_KEY
  → Copy "service_role" key   → SUPABASE_SERVICE_ROLE_KEY

STEP 4 — Add same keys to Vercel (for live site)
  → Open: https://vercel.com/dashboard → medtrack → Settings → Environment Variables
  → Add each variable from .env.local (copy all lines except comments)
  → Redeploy after saving

STEP 5 — Test locally
  → npm run dev
  → Kiosk PIN: 1234  |  Dashboard: /login (magic link to your email)

Optional later: Google Tasks — see SETUP.md
`);
