#!/usr/bin/env node
/**
 * MedTrack Setup Script
 * Generates .env.local with freshly generated secrets (never hardcoded).
 * Paste 3 values from Supabase Dashboard → Settings → API.
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const ENV_PATH = path.join(ROOT, '.env.local');

function generateVapidKeys() {
  try {
    const webpush = require('web-push');
    return webpush.generateVAPIDKeys();
  } catch (error) {
    console.error('Failed to generate VAPID keys. Run: npm install');
    process.exit(1);
  }
}

const vapid = generateVapidKeys();
const cronSecret = crypto.randomBytes(32).toString('hex');

const envContent = `# ============================================================
# MedTrack — Auto-generated by: npm run setup
# Do NOT commit this file to git.
# ============================================================

# --- Paste from Supabase Dashboard → Settings → API ---
NEXT_PUBLIC_SUPABASE_URL=PASTE_YOUR_SUPABASE_URL_HERE
NEXT_PUBLIC_SUPABASE_ANON_KEY=PASTE_YOUR_ANON_KEY_HERE
SUPABASE_SERVICE_ROLE_KEY=PASTE_YOUR_SERVICE_ROLE_KEY_HERE

# --- Auto-generated (safe to keep) ---
NEXT_PUBLIC_SITE_URL=https://medtrack-flame.vercel.app
NEXT_PUBLIC_MEDTRACK_TIMEZONE=America/New_York
KIOSK_PIN=1234
CRON_SECRET=${cronSecret}
NEXT_PUBLIC_VAPID_PUBLIC_KEY=${vapid.publicKey}
VAPID_PRIVATE_KEY=${vapid.privateKey}
VAPID_SUBJECT=mailto:caregiver@medtrack.app

# --- Optional: Google Tasks ---
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
`;

const targetPath = fs.existsSync(ENV_PATH)
  ? path.join(ROOT, '.env.local.new')
  : ENV_PATH;

fs.writeFileSync(targetPath, envContent);

if (targetPath.endsWith('.new')) {
  console.log('⚠️  .env.local already exists — wrote .env.local.new instead');
} else {
  console.log('✅ Created .env.local');
}

console.log(`
MedTrack setup file ready.

Next steps:
  1. Supabase → Settings → API → paste URL, anon key, service_role into ${path.basename(targetPath)}
  2. Use full URL: https://YOUR-PROJECT.supabase.co (not just the project id)
  3. Copy the same vars to Vercel → Environment Variables → Redeploy
  4. npm run dev  →  /kiosk (PIN 1234)  |  /login (caregiver)

See SETUP.md for full guide.
`);
